version: '3.7'

services: 
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - GENERIC_TIMEZONE=Europe/Moscow
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
    volumes: 
      - ./n8n-data:/home/node/.n8n
    restart: unless-stopped 